name: Push Checks

on:
  push:
    branches:
      - master

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Run yamlint
      run: |
        pip install yamllint
        find . -name "*.yaml" -exec yamllint -c .yamllint {} \;

    - name: Run tflint
      run: |
        wget https://github.com/terraform-linters/tflint/releases/latest/download/tflint_linux_amd64.zip
        unzip tflint_linux_amd64.zip
        sudo mv tflint /usr/local/bin/
        tflint -f compact --recursive --only=terraform_unused_declarations || true

    - name: Execute Heredoc Script
      run: |
        find . -type f -name "*.tf" -exec grep -H "<<" {} \; | tee -a tmp_heredoc.log
        line_count=$(wc -l < tmp_heredoc.log | awk '{print $1}')
        if [[ $line_count -gt 0 ]]; then
        echo "$line_count lines in tmp_heredoc.log"
        fi

    - name: Run Terraform fmt
      run: |
        terraform fmt -check --recursive
