name: Push Checks

on:
  push:
    branches:
      - master

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Run yamlint
      run: |
        pip install yamllint
        find . -name "*.yaml" -exec yamllint -c .yamllint {} \;

    - name: Run tflint
      run: |
        wget https://github.com/terraform-linters/tflint/releases/latest/download/tflint_linux_amd64.zip
        unzip tflint_linux_amd64.zip
        sudo mv tflint /usr/local/bin/
        tflint -f compact --recursive --only=terraform_unused_declarations || true

    - name: Execute Heredoc Script
      run: |
        IGNORED_FILES="$(grep -Ev '^#|^$' < heredoc_check.ignore)"
        if [[ -z "$IGNORED_FILES" ]]; then
            echo "Ignored files: None" | tee tmp_heredoc.log
            find . -type f -name "*.tf" -exec grep -H "<<" {} \; | tee -a tmp_heredoc.log
        else
            echo "Ignored files:" | tee tmp_heredoc.log
            echo "${IGNORED_FILES}" | tee -a tmp_heredoc.log
            for FILE in ${IGNORED_FILES}; do
                find . -type f -name "*.tf" -not -wholename "${FILE}" -exec grep -H "<<" {} \; | tee -a tmp_heredoc.log
            done
        fi
        cat tmp_heredoc.log

    - name: Run Terraform fmt
      run: |
        terraform fmt -check --recursive
